.assets:
  stage: build
  image: fireworkweb/fwd:1.0-rc
  services:
    - docker:dind
  tags:
    - dind
  cache:
    paths:
      - node_modules/
      - .yarn/
  before_script:
    - mkdir -p .yarn
    - fwd yarn install --no-progress --silent --force --cache-folder=.yarn/
  script:
    - fwd yarn production
  artifacts:
    paths:
      - public/js
      - public/css
      - public/img
      - public/mix-manifest.json
      - node_modules
    expire_in: 1 week
  dependencies: []
