include:
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/testing-base.yml

.dusk:
  extends: .testing-base
  script:
    - fwd dusk
  artifacts:
    paths:
      - storage/logs
      - tests/Browser/screenshots
      - tests/Browser/console
    when: on_failure
    expire_in: 1 week
  variables:
    TESTING_ENV_FILE: .env.dusk.local
