.php-cs-fixer:
  stage: QA
  image: fireworkweb/fwd:1.0-rc
  services:
    - docker:dind
  tags:
    - dind
  script:
    - fwd php-cs-fixer fix app --format=txt --dry-run --diff --verbose
    - fwd php-cs-fixer fix tests --format=txt --dry-run --diff --verbose
    - fwd php-cs-fixer fix resources/lang --format=txt --dry-run --diff --verbose
    - fwd php-cs-fixer fix config --format=txt --dry-run --diff --verbose
    - fwd php-cs-fixer fix database --format=txt --dry-run --diff --verbose
  dependencies: []
