include:
  - https://raw.githubusercontent.com/fireworkweb/fwd/1.0-rc/gitlab-ci/testing-base.yml

.phpunit:
  extends: .testing-base
  script:
    - fwd phpunit --colors=never -vvv
  artifacts:
    paths:
      - storage/logs
    when: on_failure
    expire_in: 1 week
  variables:
    TESTING_ENV_FILE: .env.testing
