name: lint-test

on:
  push:
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        php: [7.2, 7.3, 7.4]
        os: [ubuntu-latest, macos-latest]

    name: PHP v${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: mbstring
          coverage: xdebug
          tools: php-cs-fixer

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction

      - name: Build fwd
        run: php fwd app:build --build-version=testing

      - name: Execute linter
        run: php-cs-fixer fix --dry-run --diff --verbose

      - name: Execute tests
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
